CREATE TABLE todo(
    id BIGSERIAL PRIMARY KEY NOT NULL,
    title TEXT NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    updatedAt DATE NOT NULL DEFAULT NOW(),
    createdAt DATE NOT NULL DEFAULT NOW()
)
